### PR TITLE
Selectively allow anonymous access

### PR DESCRIPTION
**Pull request by dnndevelopernc**

### CODE REVIEW

**Comment by joemcbride** [comment]
This has conflicts after merging your other two PRs.  I’m also a little unsure about the change in behavior.  I’ll need to pull this down to play with it a bit.  I’m also thinking there may be a different way to accomplish what you want.

**Comment by dnndevelopernc** [comment]
Conflicts fixed.  No problem at all. Completely understand - I am open to any suggestions that accomplish the same outcome.

**Comment by sungam3r** [comment]
@dnndevelopernc Please put some words about what you want to achive.

**Comment by sungam3r** [comment]
I understand that you need to "skip" or "override" (in terms of priorities) the check of one or more upper query levels.

**Comment by sungam3r** [comment]
Found #44

**Comment by tonygomez** [comment]
> @dnndevelopernc Please put some words about what you want to achive.

The purpose of this PR is if an endpoint is flagged as public ignore mutation/query level policies. Its has been a while since this PR was created so there may be something I am leaving out. We have been using this code in production for several years with no issues.

**Comment by sungam3r** [comment]
@dnndevelopernc Thanks for PR but I propose to close it. See details in #44. Also note that `AuthorizationMetadataExtensions` class was renamed and moved into GraphQL.NET since it is just a thin wrapper around metadata handling. See https://github.com/graphql-dotnet/graphql-dotnet/pull/2451 . I repeat that the main problem with this PR is that it is try to solve a much broader problem at the same time using rather limited tools. The result obtained works in a narrow spectrum of cases. It will have to be specifically documented and maintained.

> We have been using this code in production for several years with no issues.

@tonygomez I have no doubt that this is true 👍 . Understand me correctly but I can only think about the proposed solution like some sort of a hack.

**Comment by sungam3r** [comment]
>  I’m also thinking there may be a different way to accomplish what you want.

Agree. See https://github.com/graphql-dotnet/authorization/issues/44#issuecomment-991938606.

**Comment by tonygomez** [comment]
> @dnndevelopernc Thanks for PR but I propose to close it. See details in #44. Also note that `AuthorizationMetadataExtensions` class was renamed and moved into GraphQL.NET since it is just a thin wrapper around metadata handling. See [graphql-dotnet/graphql-dotnet#2451](https://github.com/graphql-dotnet/graphql-dotnet/pull/2451) . I repeat that the main problem with this PR is that it is try to solve a much broader problem at the same time using rather limited tools. The result obtained works in a narrow spectrum of cases. It will have to be specifically documented and maintained.
> 
> > We have been using this code in production for several years with no issues.
> 
> @tonygomez I have no doubt that this is true 👍 . Understand me correctly but I can only think about the proposed solution like some sort of a hack.

Sounds good. Thank you for the update.

**Pull request closed without merging**
