### PR TITLE
Use Microsoft.AspNetCore.Authorization but only for .NET Core

### PR DESCRIPTION
**Pull request by RehanSaeed**
This is a fairly big PR that makes use of the `Microsoft.AspNetCore.Authorization` NuGet package when using .NET Core, while continueing to use the duplicate code for full .NET Framework 4.6. It lets you do this:

```
    .AddTransient<IValidationRule, AuthorizationValidationRule>()
    .AddAuthorization(
        options =>
        {
            options.AddPolicy("Admin", x => x.RequireClaim("role", "admin"));
        })
```

See https://github.com/graphql-dotnet/authorization/issues/11 for more details.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
It would be nice if we could add an `AddGraphQLAuthorization` extension method to the `IGraphQLBuilder` interface but that exists in a separate repository. Perhaps this project should move into the `Server` repo?

**Comment by RehanSaeed** [comment]
I forgot to mention that the codebase uses `GetAwaiter().GetResult()` a fair bit. Would be good to switch to using `Task` everywhere for performance.

**Comment by joemcbride** [comment]
There's a lot here so I haven't been able to fully look at it yet.  Honestly I mostly just don't want to have to deal with the complexity of maintaining such a big fork in the codebase so admittedly this has languished a bit.

> I forgot to mention that the codebase uses GetAwaiter().GetResult() a fair bit. Would be good to switch to using Task everywhere for performance.

I'm not sure where all you're referring to, though the ones I'm aware of are due to Validation Rules in the core project do not yet support `Task`, whereas this library was built to support `Task`.  So what really needs the update is the Validation Rules in the core GraphQL project.

**Comment by RehanSaeed** [comment]
Hesiatation is understandable. Take your time.

**Comment by benmccallum** [comment]
Nice one @RehanSaeed ! I'd be keen for this as I'm about to implement a bunch of authorization requirements and am on dotnet core.

**Comment by RehanSaeed** [comment]
@benmccallum This PR is not going to be merged. See https://github.com/graphql-dotnet/authorization/issues/11 for more info and my next steps.

**Comment by benmccallum** [comment]
Thanks @RehanSaeed , will continue conversation over there!

**Comment by RehanSaeed** [comment]
New PR raised in the Server project at https://github.com/graphql-dotnet/server/pull/171

**Pull request closed without merging**
